import * as account from './account.js';
import * as store from './store.js';
import { byId } from './missions.js';
const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const roleName = r => r === 'parent' ? '학부모용' : r === 'student' ? '학생용' : '기존 가족 계정';
const roles = `<fieldset class="role-options"><legend>누가 사용할 계정인가요?</legend><label><input type="radio" name="role" value="student" required><span><b>학생용</b><small>실험하고 발견을 기록해요</small></span></label><label><input type="radio" name="role" value="parent" required><span><b>학부모용</b><small>연결된 학생의 탐구를 살펴봐요</small></span></label></fieldset>`;
export function createAccountUI(root, toast, updateShell) {
  const $ = s => root.querySelector(s);
  async function renderAccount(mode='login') {
    const signup=mode==='signup'; let acc=account.current();
    root.innerHTML=`<div class="portal-container account-page"><a class="text-link" href="#home">← 탐구 홈으로</a><div class="account-layout"><aside class="account-intro"><span class="section-label">MY ASTROBOX</span><h1>각자의 탐험,<br>함께하는 발견.</h1><p>학생도 학부모도 나만의 계정으로.<br>가입 후 가족 계정을 연결해요.</p><ol class="account-steps"><li>학생용 · 학부모용 선택</li><li>별명과 PIN으로 회원가입</li><li>가족 연결 코드로 함께하기</li></ol><p class="small">이메일·실명·전화번호를 받지 않아요.</p><a class="button light" href="#family">가족 계정 연결 →</a></aside><section class="account-form-panel" id="accountPanel"></section></div></div>`;
    const panel=$('#accountPanel');
    if(acc){
      panel.innerHTML='<p role="status">계정 정보를 확인하고 있어요…</p>';
      let error='';try{await account.family();acc=account.current();}catch(e){error=e.message;}if(!panel.isConnected)return;
      panel.innerHTML=`<span class="section-label">${roleName(acc.role)}</span><h2>${esc(acc.childName)}님, 반가워요!</h2><div class="family-code"><span>나의 로그인 코드</span><b>${esc(acc.code)}</b><small>PIN과 함께 보관하고 다른 사람과 공유하지 마세요.</small></div>${error?`<p role="alert">${esc(error)}</p>`:''}${acc.role==='legacy'?`<form id="legacyRole"><h3>기존 계정은 그대로 이어가요</h3><p>이 계정을 사용할 사람을 선택해 주세요. 기존 기록과 로그인 코드가 유지돼요. 함께 쓰던 가족은 다른 유형으로 새로 가입한 뒤 연결해 주세요.</p>${roles}<button class="button blue" type="submit">이 유형으로 계속하기</button><p role="status" id="roleMessage"></p></form>`:`<a class="button blue" href="#family">가족 계정 연결 · 관리 →</a><div class="account-links"><a href="${acc.role==='parent'?'#report':'#learning'}">${acc.role==='parent'?'연결된 학생 리포트':'나의 탐구방'} →</a><a href="#plans">이용권 관리 →</a></div>`}<button class="button light" id="syncNow">내 기록 동기화하기</button><p id="syncMsg" role="status"></p><button id="logout" class="text-button">로그아웃</button><p class="small muted">기록은 계정별로 보관돼요. 로그아웃하면 가입 전 비회원 기록으로 돌아가요.</p>`;
      $('#logout').onclick=()=>{account.logout();updateShell();toast('로그아웃했어요.');renderAccount();};
      $('#syncNow').onclick=async e=>{const button=e.currentTarget,message=$('#syncMsg');button.disabled=true;message.textContent='동기화 중…';const r=await store.sync();if(!button.isConnected)return;button.disabled=false;message.textContent=r?'내 기록을 동기화했어요.':'동기화하지 못했어요. 연결과 로그인 상태를 확인해 주세요.';};
      if($('#legacyRole'))$('#legacyRole').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,button=form.querySelector('button');button.disabled=true;try{await account.family('role',{role:new FormData(form).get('role')});updateShell();if(form.isConnected)renderAccount();}catch(err){if(form.isConnected){$('#roleMessage').textContent=err.message;button.disabled=false;}}};return;
    }
    panel.innerHTML=`<nav class="account-tabs" aria-label="계정 시작"><a href="#account" ${signup?'':'aria-current="page"'}>로그인</a><a href="#account/signup" ${signup?'aria-current="page"':''}>회원가입</a></nav><h2>${signup?'나의 계정을 만들어요':'다시 만나 반가워요!'}</h2><p>${signup?'학생과 학부모가 각각 가입한 뒤 가족으로 연결할 수 있어요.':'나의 로그인 코드와 PIN으로 이어가세요. 기존 가족 코드도 그대로 쓸 수 있어요.'}</p><form id="accountForm">${signup?`${roles}<label for="cName">나의 별명</label><input id="cName" name="nickname" maxlength="12" required autocomplete="nickname" placeholder="실명 대신 별명을 써 주세요">`:'<label for="lCode">로그인 코드</label><input id="lCode" name="username" maxlength="6" minlength="6" pattern="[A-Za-z0-9]{6}" required autocomplete="username" autocapitalize="characters" spellcheck="false" placeholder="영문·숫자 6자리">'}<label for="accountPin">PIN 4자리</label><div class="pin-field"><input id="accountPin" name="password" type="password" inputmode="numeric" pattern="[0-9]{4}" minlength="4" maxlength="4" required autocomplete="${signup?'new-password':'current-password'}" placeholder="숫자 4자리"><button type="button" id="showPin" aria-pressed="false">보기</button></div>${signup?'<label for="confirmPin">PIN 다시 입력</label><input id="confirmPin" type="password" inputmode="numeric" pattern="[0-9]{4}" minlength="4" maxlength="4" required autocomplete="new-password"><p class="small muted">로그인 코드는 자동 발급돼요. 코드·PIN 복구 기능은 아직 없으니 꼭 보관해 주세요. 가입 전 비회원 기록은 별도로 남아 있어요.</p>':''}<button type="submit" class="button blue">${signup?'회원가입':'로그인'} →</button><p id="accMsg" role="status" aria-live="polite"></p></form><div class="account-links"><a href="#family">가족 계정 연결 →</a><a href="#help">코드·PIN 도움말 →</a></div><div class="guest-start"><a href="#rocket">로그인 없이 체험하기 →</a></div>`;
    const form=$('#accountForm'),pin=$('#accountPin'),message=$('#accMsg');$('#showPin').onclick=e=>{const show=pin.type==='password';pin.type=show?'text':'password';e.target.textContent=show?'숨기기':'보기';e.target.setAttribute('aria-pressed',String(show));};
    form.onsubmit=async e=>{e.preventDefault();if(signup&&pin.value!==$('#confirmPin').value){message.textContent='두 PIN이 같지 않아요. 다시 확인해 주세요.';return;}const button=form.querySelector('[type=submit]');button.disabled=true;message.textContent='연결하고 있어요…';try{if(signup)await account.create($('#cName').value.trim(),pin.value,new FormData(form).get('role'));else await account.login($('#lCode').value.trim().toUpperCase(),pin.value);await store.sync();updateShell();if(form.isConnected){toast(signup?'가입했어요! 로그인 코드를 보관해 주세요.':'로그인했어요.');renderAccount();}}catch(err){if(form.isConnected){message.textContent=err.message;button.disabled=false;}}};
  }
  async function renderFamily(reportMode=false) {
    const acc=account.current();
    root.innerHTML=`<div class="portal-container family-page"><header class="page-heading"><span class="section-label">FAMILY · 함께하는 탐구</span><h1>${reportMode?'연결된 학생의 탐구 리포트':'가족 계정 연결'}</h1><p>각자 로그인하고, 가족과 발견을 함께 살펴봐요.</p></header><div id="familyBody" role="region" aria-label="가족 연결 관리"></div></div>`;
    const body=$('#familyBody');
    if(!acc){body.innerHTML='<div class="portal-empty"><h2>먼저 내 계정으로 로그인해 주세요</h2><p>학생과 학부모가 각각 가입한 뒤, 한쪽에서 만든 연결 코드를 다른 쪽에 입력해요.</p><a class="button blue" href="#account">로그인</a> <a class="button light" href="#account/signup">회원가입</a></div>';return;}
    body.innerHTML='<p role="status">연결된 가족을 불러오고 있어요…</p>';
    let data;try{data=await account.family();}catch(e){if(body.isConnected){body.innerHTML=`<p role="alert">${esc(e.message)}</p><button class="button light" id="retryFamily">다시 불러오기</button>`;$('#retryFamily').onclick=()=>renderFamily(reportMode);}return;}if(!body.isConnected)return;
    if(data.me.role==='legacy'){body.innerHTML='<div class="portal-empty"><h2>기존 계정의 유형을 먼저 선택해 주세요</h2><p>기록과 로그인 코드를 유지하면서 학생용 또는 학부모용으로 이어갈 수 있어요.</p><a class="button blue" href="#account">내 계정에서 선택하기 →</a></div>';return;}
    const parent=data.me.role==='parent';
    body.innerHTML=`<div class="save-notice"><span><b>${esc(data.me.childName)} · ${roleName(data.me.role)}</b><br>연결하면 학부모가 학생의 서버에 저장된 탐구 기록과 발견 카드를 볼 수 있어요. 로그인 코드·PIN과 이용권은 각자 유지돼요.</span></div><section class="linked-family"><div class="section-heading"><h2>연결된 ${parent?'학생':'학부모'} <span class="count-chip">${data.linked.length}</span></h2><a class="text-link" href="#account">내 계정 →</a></div>${data.linked.length?data.linked.map(f=>`<article class="family-member"><div><b>${esc(f.name)}</b><span>${roleName(f.role)}</span></div><div class="family-member-actions">${parent?`<button class="button light" data-report="${f.id}">탐구 리포트 보기</button>`:''}<button class="text-button" data-unlink="${f.id}">연결 해제</button></div><div class="unlink-confirm" id="unlink-${f.id}" hidden><p>이 가족과 연결을 해제할까요? 각자의 기록은 유지되고 학부모의 리포트 접근은 종료돼요.</p><button class="button light" data-confirm="${f.id}">연결 해제 확인</button><button class="text-button" data-cancel="${f.id}">취소</button></div></article>`).join(''):`<div class="portal-empty"><h3>아직 연결된 ${parent?'학생이':'학부모가'} 없어요</h3><p>아래에서 연결 코드를 만들거나 가족에게 받은 코드를 입력해 주세요.</p></div>`}<p id="familyMessage" role="status"></p></section><section id="studentReport" aria-live="polite"></section><div class="family-connect-grid"><form id="makeInvite" class="family-connect-card"><span class="section-label">01 · 코드를 보내는 사람</span><h2>연결 코드 만들기</h2><p>새 코드는 10분 동안 한 번만 쓸 수 있어요. 새로 만들면 이전 코드는 만료돼요.</p><label class="consent"><input type="checkbox" required> 이 코드를 받은 ${parent?'학생과':'학부모와'} 연결하고, 학부모에게 학생의 탐구 기록을 공유할게요.</label><button class="button blue" type="submit">연결 코드 만들기</button><div id="inviteResult" role="status"></div></form><form id="joinFamily" class="family-connect-card"><span class="section-label">02 · 코드를 받는 사람</span><h2>받은 코드로 연결하기</h2><label for="inviteCode">가족 연결 코드 12자리</label><input id="inviteCode" name="inviteCode" required maxlength="14" pattern="[A-Fa-f0-9 -]{12,14}" autocapitalize="characters" autocomplete="off" spellcheck="false" placeholder="예: A1B2-C3D4-E5F6"><p class="small muted">로그인 코드 6자리가 아닌, 가족에게 받은 연결 코드를 넣어요.</p><label class="consent"><input type="checkbox" required> 가족과 연결하고 학부모가 학생의 탐구 기록을 보는 데 동의해요.</label><button class="button blue" type="submit">가족 계정 연결하기</button><p id="joinMessage" role="status"></p></form></div>`;
    const report=$('#studentReport');let reportRequest=0;
    body.querySelectorAll('[data-report]').forEach(button=>button.onclick=async()=>{const request=++reportRequest;report.innerHTML='<p role="status">학생 기록을 불러오는 중…</p>';try{const d=await account.family('report',{id:button.dataset.report});if(!report.isConnected||request!==reportRequest)return;report.innerHTML=`<div class="family-report"><div class="section-heading"><h2>${esc(d.student.name)}의 탐구 기록</h2><button class="text-button" id="closeReport">리포트 닫기</button></div><p class="small muted">학생 계정이 서버에 동기화한 기록이에요. 학생의 기록을 수정하거나 내 계정에 합치지 않아요.</p><div class="learning-stats"><div><span>해본 실험</span><b>${d.events.filter(e=>e.type==='experiment').length}<small>회</small></b></div><div><span>발견 카드</span><b>${d.cards.length}<small>장</small></b></div><div><span>코치와 대화</span><b>${d.events.filter(e=>e.type==='coach').length}<small>회</small></b></div></div><div class="family-requests"><h3>학생이 보낸 요청</h3>${d.requests.length?d.requests.map(r=>`<div class="family-request"><p>${esc(byId(r.next_mission)?.title || r.next_mission)}</p><button class="button light" data-decision="approve" data-request="${r.id}">무료 미션 팩 열고 승인</button> <button class="text-button" data-decision="decline" data-request="${r.id}">나중에</button></div>`).join(''):'<p class="small muted">기다리는 요청이 없어요.</p>'}<p class="small muted">승인하면 학생 계정에 0원 데모 이용권이 열려요. 실제 청구는 없어요.</p><p id="decisionMessage" role="status"></p></div>${d.cards.length?d.cards.slice().reverse().map(c=>`<article class="notebook-card"><h3>${esc(c.title)}</h3><dl><dt>처음 생각</dt><dd>${esc(c.initial)}</dd><dt>관찰</dt><dd>${esc(c.observation)}</dd><dt>지금 내 생각</dt><dd>${esc(c.explanation)}</dd>${c.next?`<dt>다음 질문</dt><dd>${esc(c.next)}</dd>`:''}</dl></article>`).join(''):'<p>아직 서버에 저장된 발견 카드가 없어요. 학생 계정에서 탐구하고 기록을 동기화해 주세요.</p>'}</div>`;report.querySelectorAll('[data-decision]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await account.family(b.dataset.decision,{id:d.student.id,requestId:b.dataset.request});if(b.isConnected)button.click();}catch(e){if(b.isConnected){$('#decisionMessage').textContent=e.message;b.disabled=false;}}});$('#closeReport').onclick=()=>{reportRequest++;report.innerHTML='';};}catch(e){if(report.isConnected&&request===reportRequest)report.innerHTML=`<p role="alert">${esc(e.message)}</p>`;}});
    body.querySelectorAll('[data-unlink]').forEach(b=>b.onclick=()=>{$('#unlink-'+b.dataset.unlink).hidden=false;});
    body.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>{$('#unlink-'+b.dataset.cancel).hidden=true;});
    body.querySelectorAll('[data-confirm]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await account.family('unlink',{id:b.dataset.confirm});if(body.isConnected){toast('가족 연결을 해제했어요.');renderFamily(reportMode);}}catch(e){if(b.isConnected){$('#familyMessage').textContent=e.message;b.disabled=false;}}});
    $('#makeInvite').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,button=form.querySelector('button'),result=$('#inviteResult');button.disabled=true;result.textContent='코드를 만들고 있어요…';try{const d=await account.family('invite');if(!form.isConnected)return;result.innerHTML=`<div class="family-code"><span>가족에게만 전달해 주세요</span><b>${d.code.match(/.{4}/g).join('-')}</b><small>${new Date(d.expiresAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}까지 · 1회용</small></div><button type="button" class="text-button" id="cancelInvite">이 연결 코드 취소</button><p class="small">가족이 연결한 뒤 아래에서 목록을 새로 불러오세요.</p><button type="button" class="button light" id="reloadFamily">연결된 가족 새로고침</button>`;$('#reloadFamily').onclick=()=>renderFamily(reportMode);$('#cancelInvite').onclick=async ev=>{const cancel=ev.currentTarget;cancel.disabled=true;try{await account.family('cancel');if(result.isConnected)result.textContent='연결 코드를 취소했어요.';}catch(err){if(result.isConnected){result.textContent=err.message;}}};}catch(err){if(result.isConnected)result.textContent=err.message;}finally{if(button.isConnected)button.disabled=false;}};
    $('#joinFamily').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,button=form.querySelector('button');button.disabled=true;try{await account.family('connect',{code:$('#inviteCode').value});if(form.isConnected){toast('가족 계정이 연결됐어요!');renderFamily(reportMode);}}catch(err){if(form.isConnected){$('#joinMessage').textContent=err.message;button.disabled=false;}}};
  }
  return {renderAccount,renderFamily};
}
