// 귀여운 효과 — 폭죽(예측대로), 흔들림(추락), 펭귄 리액션, 작은 효과음(WebAudio, 파일 없음)
let actx = null; function beep(freqs, dur = 0.12, type = 'sine', gain = 0.06) { try { actx ??= new (window.AudioContext || window.webkitAudioContext)(); const t0 = actx.currentTime; freqs.forEach((f, i) => { const o = actx.createOscillator(), g = actx.createGain(); o.type = type; o.frequency.value = f; g.gain.setValueAtTime(0, t0 + i * dur); g.gain.linearRampToValueAtTime(gain, t0 + i * dur + 0.01); g.gain.exponentialRampToValueAtTime(0.0001, t0 + (i + 1) * dur); o.connect(g).connect(actx.destination); o.start(t0 + i * dur); o.stop(t0 + (i + 1) * dur + 0.02); }); } catch {} }
export const sound = { win: () => beep([523, 659, 784, 1047], 0.11), lose: () => beep([330, 262], 0.18, 'triangle'), pop: () => beep([880], 0.06, 'square', 0.03), launch: () => beep([196, 262, 330, 392, 523], 0.07, 'sawtooth', 0.03) };
export function confetti(x = window.innerWidth / 2, y = window.innerHeight / 2, n = 60) {
  const colors = ['#ff6237', '#46d49a', '#5aa9ff', '#ffb454', '#fff'];
  for (let i = 0; i < n; i++) { const el = document.createElement('i'); el.className = 'fx-confetti'; el.style.left = x + 'px'; el.style.top = y + 'px'; el.style.background = colors[i % colors.length]; const a = Math.random() * Math.PI * 2, d = 80 + Math.random() * 220; el.style.setProperty('--dx', Math.cos(a) * d + 'px'); el.style.setProperty('--dy', Math.sin(a) * d - 120 + 'px'); el.style.setProperty('--r', Math.random() * 720 + 'deg'); document.body.appendChild(el); setTimeout(() => el.remove(), 1300); }
}
export function shake(el) { if (!el) return; el.classList.remove('fx-shake'); void el.offsetWidth; el.classList.add('fx-shake'); setTimeout(() => el.classList.remove('fx-shake'), 600); }
export function penguinReact(mood) { document.querySelectorAll('.penguin').forEach((p) => { p.classList.remove('happy', 'sad', 'think'); void p.offsetWidth; p.classList.add(mood); setTimeout(() => p.classList.remove(mood), 1400); }); }
export function stars(el) { if (!el) return; for (let i = 0; i < 8; i++) { const s = document.createElement('i'); s.className = 'fx-star'; s.textContent = '✦'; s.style.left = 20 + Math.random() * 60 + '%'; s.style.top = 20 + Math.random() * 60 + '%'; s.style.animationDelay = Math.random() * 0.3 + 's'; el.appendChild(s); setTimeout(() => s.remove(), 1200); } }
