import { createAccountUI } from './account-ui.js';
import { MISSIONS } from './missions.js';
import * as store from './store.js';
import * as account from './account.js';
import * as unlock from './unlock.js';

const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const icons = {
  orbit: '<circle cx="12" cy="12" r="4"/><ellipse cx="12" cy="12" rx="11" ry="5" transform="rotate(-30 12 12)"/>',
  rocket: '<path d="M14 5c3-3 6-3 7-2 1 1 1 4-2 7l-7 7-5-5zM8 11H3l4-5h6M13 16v5l5-4v-6M7 17l-3 3M4 16l-2 2M8 20l-2 2"/><circle cx="16" cy="7" r="2"/>',
  star: '<path d="m12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1z"/>',
  time: '<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>',
  book: '<path d="M12 5v16M12 5C8 2 4 3 2 4v15c3-1 7-1 10 2 3-3 7-3 10-2V4c-3-1-7-2-10 1z"/>',
  lab: '<path d="M8 2h8M9 2v7L3 19c-1 2 1 3 2 3h14c2 0 3-1 2-3L15 9V2M6 15h12"/>',
  arrow: '<path d="M4 12h16m-6-6 6 6-6 6"/>',
  check: '<path d="m5 12 4 4L19 6"/>',
  search: '<circle cx="10" cy="10" r="7"/><path d="m15 15 6 6"/>',
  user: '<circle cx="12" cy="8" r="4"/><path d="M4 22v-2a8 8 0 0 1 16 0v2"/>',
};
export const icon = name => `<svg class="ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name] || icons.orbit}</svg>`;
export const ACTIVITIES = [
  { id: 'rocket', href: '#rocket', title: '내 로켓을 우주로!', desc: '연료를 얼마나 실어야 지구 주위를 돌 수 있을까요?', category: 'rocket', label: '로켓 · 발사', level: '처음 탐구', art: 'rocket', tag: '3D 발사 · 예측과 실험' },
  ...MISSIONS.map((m, i) => ({ id: m.id, href: '#m/' + m.id, title: m.title, desc: m.intro, category: 'orbit', label: '지구 · 달 · 궤도', level: i < 2 ? '차근차근' : '한 걸음 더', art: 'orbit', tag: m.concept })),
  { id: 'stars', href: '#stars', title: '내 손으로 별 키우기', desc: '별의 무게를 바꾸고, 어떤 모습으로 자랄지 예측해요.', category: 'stars', label: '별 · 우주', level: '처음 탐구', art: 'star', tag: '별의 일생 · 별 도감' },
  { id: 'timeline', href: '#timeline', title: '138억 년 시간 여행', desc: '빅뱅부터 오늘까지. 시간 속에 숨은 이야기를 찾아요.', category: 'stars', label: '별 · 우주', level: '처음 탐구', art: 'time', tag: '시간 여행 · 우주 달력 · 퀴즈' },
  { id: 'lab', href: '#lab', title: '마음껏, 자유 실험실', desc: '속력과 중력, 발사각을 바꾸며 나만의 질문을 찾아요.', category: 'lab', label: '자유 실험', level: '한 걸음 더', art: 'lab', tag: '조건 조절 · 궤도 관찰' },
];
export const FILTERS = [['all', '전체 탐구'], ['rocket', '로켓 · 발사'], ['orbit', '지구 · 달 · 궤도'], ['stars', '별 · 우주'], ['lab', '자유 실험']];
export function filterActivities(category = 'all', query = '') {
  const q = query.trim().toLocaleLowerCase();
  return ACTIVITIES.filter(a => (category === 'all' || a.category === category) && `${a.title} ${a.desc} ${a.tag} ${a.label}`.toLocaleLowerCase().includes(q));
}
export function recentActivity(events) {
  return [...events].reverse().map(e => ACTIVITIES.find(a => a.id === e.mission)).find(Boolean) || ACTIVITIES[0];
}
const heading = (eyebrow, title, desc) => `<header class="page-heading"><span class="section-label">${eyebrow}</span><h1>${title}</h1><p>${desc}</p></header>`;
const empty = (title, desc, href = '#explore', label = '탐구 고르기') => `<div class="portal-empty">${icon('book')}<h2>${title}</h2><p>${desc}</p><a class="button blue" href="${href}">${label} ${icon('arrow')}</a></div>`;
function activityCard(a, sum) {
  const locked = !unlock.isUnlocked(a.id), b = sum.byMission[a.id];
  return `<a class="activity-card" href="${a.href}"><div class="activity-art art-${a.art}"><span class="art-orbit-ring"></span><span class="art-body">${icon(a.art)}</span><span class="art-dot"></span><span class="access-badge">${locked ? '미션 팩' : '무료 탐구'}</span></div><div class="activity-copy"><div class="activity-meta">${a.label}<span>${a.level}</span></div><h3>${esc(a.title)}</h3><p>${esc(a.desc)}</p><div class="activity-bottom"><span>${b?.experiments ? `실험 ${b.experiments}회 · 카드 ${b.cards}장` : esc(a.tag)}</span>${icon('arrow')}</div></div></a>`;
}
export function createPortal(root, toast, updateShell) {
  const $ = s => root.querySelector(s);
  function renderHome() {
    const sum = store.summary(), acc = account.current(), recent = recentActivity(sum.events);
    root.innerHTML = `<div class="portal-container home-page">
      <section class="welcome-hero"><div class="hero-copy"><span class="hero-kicker"><i></i> 호기심이 자라는 나만의 우주 실험실</span><h1>우주가 궁금해?<br>직접 <em>해보면</em> 알지!</h1><p>로켓을 쏘고, 별을 키우고, 지구를 한 바퀴.<br>‘왜?’라는 질문을 나만의 발견으로 바꿔 봐요.</p><div class="hero-actions"><a class="button blue" href="${sum.events.length ? recent.href : '#rocket'}">${sum.events.length ? '내 탐구 이어가기' : '첫 로켓 발사하기'} ${icon('arrow')}</a><a class="button light" href="#parents">부모님, 처음이신가요?</a></div><span class="hero-note">로그인 없이 시작 · 초등 4–6학년부터 함께</span></div>
      <div class="hero-universe" role="img" aria-label="지구 주위를 여행하는 펭귄 우주비행사"><span class="orbit-ring ring-one"></span><span class="orbit-ring ring-two"></span><div class="hero-earth"></div><span class="tiny-planet"></span><span class="space-plus plus-one">✦</span><span class="space-plus plus-two">✧</span><img class="hero-penguin" src="assets/penguin-256.png" alt="" width="210" height="210"><div class="scene-bubble">오늘은 어디까지 가볼까?</div><span class="scene-label">MISSION 01 <b>지구 궤도에 도전!</b></span></div></section>
      <nav class="quick-paths" aria-label="탐구 주제 바로가기">${[['rocket','rocket','로켓 발사','내 손으로 카운트다운'],['m/m1','orbit','궤도 탐구','지구와 달 사이'],['stars','star','별 키우기','별의 미래를 찾아서'],['timeline','time','우주 시간 여행','138억 년을 한눈에'],['lab','lab','자유 실험실','궁금한 대로 바꿔 보기']].map(([href,ic,title,sub])=>`<a href="#${href}"><span class="quick-icon ${ic}">${icon(ic)}</span><span><b>${title}</b><small>${sub}</small></span></a>`).join('')}</nav>
      <section class="home-body"><div class="home-main"><div class="section-heading"><div><span class="section-label">LET’S EXPLORE</span><h2>오늘, 이런 탐구 어때요?</h2></div><a class="text-link" href="#explore">전체 탐구 ${icon('arrow')}</a></div><div class="activity-grid home-cards">${[ACTIVITIES[0],ACTIVITIES[1],ACTIVITIES[5]].map(a=>activityCard(a,sum)).join('')}</div></div>
      <aside class="my-preview"><div class="preview-head">${icon('book')} 나의 탐구방</div><h2>${acc ? `${esc(acc.childName)} 탐험가, 반가워요!` : '작은 발견을 모아 봐요'}</h2><p>내가 해본 실험과 내 말로 남긴 설명이 차곡차곡 쌓여요.</p><div class="preview-counts"><div><b>${sum.events.filter(e=>e.type==='experiment').length}</b><span>해본 실험</span></div><div><b>${sum.cards.length}</b><span>발견 카드</span></div></div><a class="button light" href="#learning">탐구방 가기 ${icon('arrow')}</a><a class="preview-login" href="#account">${acc ? '내 계정 관리' : '다른 기기에서도 이어가기 · 로그인'}</a></aside></section>
      <section class="discovery-strip"><div><span class="section-label">정답보다 궁금한 마음이 먼저</span><h2>틀려도 괜찮아.<br>다시 해보면 발견이 되니까.</h2></div><ol>${[['01','생각해 보기','어떻게 될지 먼저 골라요.'],['02','직접 바꿔 보기','조건 하나를 바꾸고 관찰해요.'],['03','내 말로 남기기','달라진 생각을 카드로 모아요.']].map(([n,t,d])=>`<li><span>${n}</span><b>${t}</b><p>${d}</p></li>`).join('')}</ol></section>
      <a class="parent-banner" href="#parents"><span>${icon('user')} 부모님을 위한 안내</span><b>아이가 무엇을 발견했는지, 함께 들여다보세요.</b><span>탐구 과정 알아보기 ${icon('arrow')}</span></a>
    </div>`;
  }
  function renderExplore() {
    const requested = location.hash.split('/')[1]; let category = FILTERS.some(([id])=>id===requested) ? requested : 'all';
    root.innerHTML = `<div class="portal-container">${heading('EXPLORE · 탐구 둘러보기','어떤 질문부터 시작할까요?','주제를 고르고 직접 바꿔 보세요. 모든 탐구는 나만의 속도로 할 수 있어요.')}<div class="catalog-tools"><div class="filter-tabs" role="group" aria-label="탐구 주제">${FILTERS.map(([id,label])=>`<button data-filter="${id}" aria-pressed="${id===category}">${label}</button>`).join('')}</div><label class="catalog-search">${icon('search')}<input id="activitySearch" type="search" placeholder="궁금한 주제 찾기" aria-label="탐구 검색"></label></div><p class="catalog-count" id="catalogCount" role="status"></p><div class="activity-grid" id="activityGrid"></div></div>`;
    const paint=()=>{const items=filterActivities(category,$('#activitySearch').value), sum=store.summary(); $('#catalogCount').textContent=`${items.length}개의 탐구 · 미션 팩도 현재 무료 데모로 열 수 있어요`; $('#activityGrid').innerHTML=items.length?items.map(a=>activityCard(a,sum)).join(''):empty('아직 그 주제는 없어요','검색어를 짧게 바꾸거나 다른 주제를 골라 보세요.'); root.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===category)));};
    root.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{category=b.dataset.filter;paint();}); $('#activitySearch').oninput=paint;paint();
  }
  function renderLearning() {
    const s=store.summary(),acc=account.current(),recent=recentActivity(s.events), exp=s.events.filter(e=>e.type==='experiment').length;
    root.innerHTML=`<div class="portal-container">${heading('MY SPACE · 나의 탐구방',`${acc?esc(acc.childName)+' 탐험가의':'나만의'} 발견이 모이는 곳`,'작은 실험도, 달라진 생각도 모두 나의 탐구 기록이에요.')}<div class="save-notice">${icon('book')}<span>${acc?'이 기기의 기록을 보여줘요. 내 계정에서 동기화 상태를 확인할 수 있어요.':'지금은 이 브라우저에 저장돼요. 로그인하면 다른 기기에서도 기록을 이어갈 수 있어요.'}</span><a href="#account">${acc?'계정 관리':'로그인'} →</a></div><div class="learning-stats"><div><span>직접 해본 실험</span><b>${exp}<small>회</small></b></div><div><span>모은 발견 카드</span><b>${s.cards.length}<small>장</small></b></div><div><span>시작한 탐구</span><b>${s.missions.length}<small>개</small></b></div></div>
    <div class="section-heading"><h2>${s.events.length?'최근 탐구 다시 해보기':'첫 발견을 시작해요'}</h2><a class="text-link" href="#explore">탐구 고르기 →</a></div><a class="continue-card" href="${recent.href}"><span class="quick-icon">${icon(recent.art)}</span><div><b>${esc(recent.title)}</b><p>${s.events.length?'조건을 다르게 바꾸면 어떤 결과가 나올까요?':'연료를 고르고 내 로켓을 직접 발사해 보세요.'}</p></div>${icon('arrow')}</a>
    <div class="section-heading"><h2>나의 발견 카드 <span class="count-chip">${s.cards.length}</span></h2><a class="text-link" href="#report">부모 리포트 →</a></div>${s.cards.length?`<div class="notebook-grid">${s.cards.slice().reverse().map(c=>`<article class="notebook-card"><span class="section-label">${new Date(c.t).toLocaleDateString('ko-KR')}</span><h3>${esc(c.title)}</h3><dl><dt>처음에는</dt><dd>${esc(c.initial)}</dd><dt>직접 보니</dt><dd>${esc(c.observation)}</dd><dt>지금 내 생각</dt><dd>${esc(c.explanation)}</dd>${c.next?`<dt>다음에는</dt><dd>${esc(c.next)}</dd>`:''}</dl></article>`).join('')}</div>`:empty('아직 빈 탐험 노트예요','탐구를 마친 뒤 발견 카드를 남기면 여기에 모여요.','#rocket','첫 로켓 발사하기')}</div>`;
  }
  function renderParents() {
    root.innerHTML=`<div class="portal-container">${heading('FOR PARENTS · 부모님 가이드','“왜 그럴까?”에 함께하는 방법','아이의 예측부터 설명까지, 정답 너머의 탐구 과정을 함께 살펴보세요.')}<section class="parent-intro"><div><span class="section-label">우주에서 시작하는 과학 탐구</span><h2>보는 데서 한 걸음 더,<br>직접 해보고 설명하는 경험.</h2><p>AstroBox는 초등 4–6학년을 첫 대상으로 만드는 우주 탐구 서비스예요. 아이가 조건을 바꾸고 결과를 관찰하며 자기 설명을 남길 수 있도록 돕습니다.</p><div class="hero-actions"><a href="#report" class="button blue">우리 아이 탐구 리포트 ${icon('arrow')}</a><a href="#explore" class="button light">탐구 둘러보기</a></div></div><div class="example-note"><span>대화 예시 · 실제 학습 기록 아님</span><p>“연료를 더 넣으면<br>어떻게 달라질까?”</p><div>예상한 결과 → 직접 발사 → 관찰 → 다시 설명</div><b>“처음 생각과 무엇이 달랐어?”</b></div></section><div class="guide-grid">${[['01','먼저, 아이가 예상하게 해주세요','맞히는 것보다 왜 그렇게 생각했는지 한마디 들어보세요.'],['02','한 번에 하나만 바꿔 보세요','연료나 속력처럼 조건 하나를 바꿔야 차이를 비교하기 쉬워요.'],['03','리포트로 대화를 이어가세요','실험 횟수와 아이가 직접 쓴 문장을 함께 보세요. 점수나 능력 진단은 아니에요.']].map(([n,t,d])=>`<article><span>${n}</span><h2>${t}</h2><p>${d}</p></article>`).join('')}</div><section class="guide-details"><h2>시작 전에 알아두세요</h2><p>물리 시뮬레이션은 교육용 근사 모형이며 실제 우주선의 성능을 재현하지 않아요. 코치는 정해진 규칙에 따라 질문과 힌트를 제공합니다. 학습 효과는 아직 검증 중이에요.</p><p>로그인 없이도 시작할 수 있어요. 학생·학부모가 각각 별명·로그인 코드·PIN으로 가입하고, 가족 계정 연결에서 탐구 기록을 공유할 수 있어요. 기록은 계정별로 보관돼요.</p><a href="#plans" class="text-link">무료 탐구와 미션 팩 알아보기 →</a></section></div>`;
  }
  async function renderPlans(checkout=false) {
    root.innerHTML=`<div class="portal-container">${heading('MEMBERSHIP · 이용권',checkout?'미션 팩 이용 신청':'궁금한 만큼, 더 탐구해요','현재는 무료 데모 운영 중이에요. 카드 정보 입력과 실제 청구는 없습니다.')}<div id="plansBody" class="plans-body"></div></div>`;
    const body=$('#plansBody'); let status;
    try { status=await unlock.orderStatus(); } catch { status={where:'unavailable',orders:[]}; }
    if(!body.isConnected)return;
    const has=unlock.isUnlocked('m2'),acc=account.current();
    if(checkout&&!has){body.innerHTML=`<div class="checkout-layout"><section class="checkout-detail"><span class="section-label">선택한 이용권</span><h2>궤도와 달 · 미션 팩</h2><p>지구 궤도부터 달 여행까지, 세 가지 미션을 이어서 탐구해요.</p><ul class="included-list">${MISSIONS.slice(1).map(m=>`<li>${icon('check')}${esc(m.title)}</li>`).join('')}</ul><div class="save-notice">${icon('user')}<span>${acc?'내 계정에 이용 내역이 저장됩니다.':'로그인 없이 신청하면 이 브라우저에만 열려요.'}</span></div>${acc?'':'<a class="text-link" href="#account">내 계정으로 로그인하기 →</a>'}</section><form id="checkoutForm" class="checkout-summary"><h2>신청 내용 확인</h2><div class="price-row"><span>무료 데모 이용권</span><strong>0원</strong></div><p>자동 결제 없음 · 카드 등록 없음</p><label class="consent"><input id="demoConfirm" type="checkbox" required> 무료 데모이며 ${acc?'가족 계정':'이 브라우저'}에 이용권이 열리는 것을 확인했어요.</label><button class="button blue" type="submit">0원으로 미션 팩 열기 ${icon('arrow')}</button><p id="checkoutMessage" role="status"></p><a class="text-link" href="#plans">이용권으로 돌아가기</a></form></div>`;
      const form=$('#checkoutForm');form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button');button.disabled=true;button.textContent='미션 팩을 여는 중…';try{const result=await unlock.checkout('pack-1');store.log('order',{pack:'pack-1',where:result.where});if(!form.isConnected)return;body.innerHTML=`<div class="checkout-success">${icon('check')}<span class="section-label">신청 완료</span><h2>새로운 탐구가 열렸어요!</h2><p>궤도와 달 미션 3개를 시작할 수 있어요.<br>결제 금액 0원 · 실제 청구 없음</p><p class="muted small">${result.where==='server'?'내 계정에 저장했어요.':'이 브라우저에 저장했어요.'}</p><a class="button blue" href="#m/m2">첫 미션 시작하기 ${icon('arrow')}</a><a class="text-link" href="#plans">이용 내역 보기 →</a></div>`;}catch(error){if(form.isConnected){$('#checkoutMessage').textContent='신청하지 못했어요. '+error.message;button.disabled=false;button.textContent='다시 신청하기';}}};return;}
    body.innerHTML=`<div class="plan-grid"><article class="plan-card"><span class="section-label">언제든 가볍게</span><h2>첫 탐구</h2><p>가입 없이 호기심부터 시작해요.</p><div class="plan-price">무료</div><ul class="included-list">${['로켓 발사와 첫 궤도 미션','별 키우기 · 우주 시간 여행','자유 실험실','발견 카드와 탐구 기록'].map(t=>`<li>${icon('check')}${t}</li>`).join('')}</ul><a class="button light" href="#rocket">바로 체험하기 ${icon('arrow')}</a></article><article class="plan-card featured"><span class="plan-ribbon">현재 무료 데모</span><span class="section-label">한 걸음 더 탐구하고 싶다면</span><h2>궤도와 달 · 미션 팩</h2><p>조건을 바꿔 가며 더 깊게 탐구해요.</p><div class="plan-price">0원 <small>데모 이용</small></div><ul class="included-list">${MISSIONS.slice(1).map(m=>`<li>${icon('check')}${esc(m.title)}</li>`).join('')}<li>${icon('check')}코치 질문 · 설명 카드 · 부모 리포트</li></ul><a class="button blue" href="${has?'#explore/orbit':'#plans/checkout'}">${has?'이용 중 · 탐구하러 가기':'무료 데모 이용 신청'} ${icon('arrow')}</a></article></div><div class="section-heading"><h2>나의 이용 내역</h2><a class="text-link" href="#account">내 계정 관리 →</a></div><div class="order-list">${status.where==='unavailable'?'<p>계정 이용 내역을 불러오지 못했어요. 로그인 상태와 연결을 확인해 주세요.</p>':status.orders.length?status.orders.map(o=>`<div class="order-row"><div><b>궤도와 달 · 미션 팩</b><span>${new Date(o.t).toLocaleDateString('ko-KR')} · ${o.where==='local'||status.where==='local'?'이 브라우저':'가족 계정'} 저장</span></div><strong>0원 <small>무료 데모</small></strong></div>`).join(''):`<p>${has?'미션 팩이 열려 있어요. 이전 이용권은 상세 신청 기록이 없을 수 있어요.':'아직 신청한 이용권이 없어요. 무료 탐구부터 시작해 보세요.'}</p>`}</div><p class="plan-footnote">가격과 유료 운영 방식은 아직 정해지지 않았습니다. 현재 이용권은 무료 데모이며 유료 정기 결제로 자동 전환되지 않아요.</p></div>`;
  }
  const { renderAccount, renderFamily } = createAccountUI(root, toast, updateShell);
  function renderHelp() {
    const faqs=[['처음인데 어디서 시작하나요?','홈에서 ‘첫 로켓 발사하기’를 눌러 보세요. 연료를 고르고 결과를 예상하면 발사할 수 있어요. 다른 주제는 ‘탐구 둘러보기’에서 찾을 수 있습니다.'],['로그인하지 않아도 되나요?','네. 첫 궤도 미션, 로켓, 별 키우기, 시간 여행, 자유 실험실은 바로 시작할 수 있어요. 기록은 이 브라우저에 남습니다. 다른 기기에서 이어가려면 내 계정으로 로그인해 주세요.'],['결제나 자동 갱신이 있나요?','현재는 무료 데모입니다. 미션 팩을 신청해도 0원이며 카드 정보를 받지 않고 자동 결제도 하지 않아요. 유료 운영 조건은 아직 정해지지 않았습니다.'],['로그인 코드나 PIN을 잊었어요.','로그인된 다른 기기가 있다면 ‘내 계정’에서 코드를 확인해 보세요. PIN을 조회하거나 직접 재설정하는 기능은 아직 없어요. 로그아웃하기 전에 코드를 보관해 주세요.'],['로켓 화면이 안 보이거나 느려요.','인터넷 연결을 확인하고 최신 브라우저에서 다시 열어 보세요. 로켓은 3D 그래픽(WebGL)을 지원하는 기기가 필요해요. 궤도 미션은 3D가 어려우면 2D로 표시됩니다.'],['기록은 어디에 저장되나요?','기본적으로 이 브라우저에 저장하고, 내 계정에 로그인하면 서버와 동기화해요. 브라우저 데이터 삭제·시크릿 모드 종료 시 로컬 기록이 사라질 수 있습니다. 로그아웃은 기록 삭제와 다릅니다.'],['가족 계정은 어떻게 연결하나요?','학생·학부모가 각각 회원가입한 뒤 ‘가족 계정 연결’에서 한쪽이 10분 동안 유효한 코드를 만들고 다른 쪽이 입력해요. 로그인 코드·PIN은 공유하지 마세요. 연결은 언제든 해제할 수 있어요.'],['부모님은 무엇을 확인할 수 있나요?','가족 계정을 연결하면 부모 리포트에서 실험 횟수, 예측과 관찰, 아이가 쓴 설명을 볼 수 있어요. 학습 성적이나 과학 능력을 진단하는 점수는 아닙니다.'],['실제 로켓과 똑같이 움직이나요?','탐구를 돕기 위한 단순화된 물리 모형이에요. 실제 우주선의 제원과 운항을 그대로 재현하지는 않습니다. 각 활동의 근사 모형 안내를 함께 확인해 주세요.']];
    root.innerHTML=`<div class="portal-container help-page">${heading('HELP · 이용 안내','궁금한 점을 함께 풀어요','시작하기부터 계정과 기록까지, 자주 묻는 질문을 모았어요.')}<div class="help-shortcuts"><a href="#account">${icon('user')} 계정 관리 →</a><a href="#plans">${icon('check')} 이용권 안내 →</a><a href="#report">${icon('book')} 탐구 리포트 →</a></div><section class="faq-list" aria-label="자주 묻는 질문">${faqs.map(([q,a])=>`<details><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</section></div>`;
  }
  return { renderHome,renderExplore,renderLearning,renderParents,renderPlans,renderAccount,renderFamily,renderHelp };
}
